### ISSUE TITLE
Create container to avoid local dependencies

### ISSUE THREAD

**Issue by absoludity** [vmware-tanzu/package-for-kubeapps#11]
Currently a bunch of dependencies are required for local installation (carvel tools, kind, yq, etc.) as documented in the CONTRIBUTING.md.

We should build and publish a container to simplify the running of the script.

**Comment by castelblanque** [comment]
Outstanding task is:

- [ ]  Completely automate the process by adding to the container the Git and GitHub credentials so that commits and releases can be automatically done from it.
