### ISSUE TITLE
Kubeapps package v10.2.2 - app v2.5.0

### ISSUE THREAD

**Issue by ppbaena** [vmware-tanzu/package-for-kubeapps#27]
**Summary:**
Generate and publish a new package corresponding to release Kubeapps v2.5.0 (chart version 10.2.2).

**Acceptance criteria**

- [x] Test passed for new package
- [x] New carvel package available for Kubeapps v2.5.0

**Comment by castelblanque** [comment]
Kubeapps Carvel package v10.2.2 (Kubeapps v2.5.0) has been released.
Please find it [in the GitHub release page](https://github.com/vmware-tanzu/package-for-kubeapps/releases/tag/v10.2.2) and [production Harbor.](https://projects.registry.vmware.com/harbor/projects/42611/repositories/kubeapps/artifacts-tab/artifacts/sha256:47c2168b4e2bb145bd7acd336eae6a188f584a7c62b731e13609482fa408b64f)
